main :: IO ()
main = do
	print(" -1 ")
	print( -1 )
	print(" 1/10 ")
	print( 1/10 )
	print(" 1`div`2 ")
	print( 1`div`2 )
	print(" div 6 5 ")
	print( div 6 5 )
	print(" div 1 5 ")
	print( div 1 5 )
	print(" 0 <= 0 ")
	print( 0 <= 0 )
	print(" 4 /= 5 ")
	print( 4 /= 5 )
	print(" 0.1 == 0.3/3 ")
	print( 0.1 == 0.3/3 )
	print(" rem 5 2 ")
	print( rem 5 2 )
	print(" mod 5 2 ")
	print( mod 5 2 )
	print(" quot 6 5 ")
	print( quot 6 5 )
	print(" quot 5 6 ")
	print( quot 5 6 )
	print(" sin 0 ")
	print( sin 0 )
	print(" pi ")
	print( pi )
	print(" sin 2*pi ")
	print( sin 2*pi )
	print(" sin (2*pi) ")
	print( sin (2*pi) )
	print(" '\\0' ")
	print( '\0' )
	print(" 'a' < 'A' ")
	print( 'a' < 'A' )
	print(" '9' < '0' ")
	print( '9' < '0' )
	print(" '\\0' < '0' ")
	print( '\0' < '0' )
	print(" '1+2' ")
	print( "1+2" )
	print(" 'ba' < 'aba' ")
	print( "ba" < "aba" )
	print(" 'ay' < 'y' ")
	print( "ay" < "y" )
	print(" '\\0abc' ")
	print( "\0abc" )
	print(" 2**1023 ")
	print( 2**1023 )
	print(" 2^1023 ")
	print( 2^1023 )
	print(" 2.0^1023 ")
	print( 2.0^1023 )
	print(" 2^0 ")
	print( 2^0 )
	print(" succ 4 ")
	print( succ 4 )
	print(" pred 4 ")
	print( pred 4 )
	print(" sqrt 3 ")
	print( sqrt 3 )
	print(" sqrt (-1) ")
	print( sqrt (-1) )
	print(" acos 3 ")
	print( acos 3 )
	print(" abs (-7) ")
	print( abs (-7) )
	print(" max (-2) 7 ")
	print( max (-2) 7 )
	print(" log 10 ")
	print( log 10 )
	print(" True < False ")
	print( True < False )
	print(" not True ")
	print( not True )
	print(" True || False ")
	print( True || False )
	print(" False && True ")
	print( False && True )
